name: machine
channels:
  - defaults
dependencies:
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - libffi=3.2.1
  - openssl=1.1.1k
  - pip=21.1.2
  - python=3.7.3
  - setuptools=52.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - appnope==0.1.2
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cffi==1.14.5
    - chardet==4.0.0
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.7.1
    - entrypoints==0.3
    - idna==2.10
    - imageio==2.9.0
    - imbalanced-learn==0.8.0
    - importlib-metadata==4.5.0
    - ipykernel==5.5.5
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - notebook==6.4.0
    - numpy==1.21.0
    - opencv-python==4.5.2.54
    - packaging==20.9
    - pandas==1.2.5
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.2.0
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.19
    - psycopg2==2.9.1
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyzmq==22.1.0
    - qtconsole==5.1.0
    - qtpy==1.9.0
    - requests==2.25.1
    - scikit-image==0.18.1
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - seaborn==0.11.1
    - send2trash==1.7.1
    - six==1.16.0
    - terminado==0.10.1
    - testpath==0.5.0
    - threadpoolctl==2.1.0
    - tifffile==2021.6.14
    - tornado==6.1
    - traitlets==5.0.5
    - typing-extensions==3.10.0.0
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.4.1
