name: Test Jupyter Notebook 
on:
  push:
    branches:
      - main

  pull_request:
    types: [synchronize, review_requested]

jobs:
  build:
    name: Test solution folder with Python ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        version: [3.7.3, 3.8, 3.9]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - shell: bash -l {0}
        run: echo ${{ runner.os }}

      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ml-fundamental
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -r requirements.txt
          pip install flake8_nb
          
      - name: Execute Flake8 to test
        shell: bash -l {0}
        run: |
          for i in solution/**; do 
            flake8_nb --select=E9,F63,F7 --notebook-cell-format '{nb_path}:code_cell#{code_cell_count}' "$i"
          done